[build]
  publish = "."

[[edge_functions]]
  function = "occasions"
  path = "/occasions/*"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/occasions/*"
  [headers.values]
    Cache-Control = "public, max-age=1800, stale-while-revalidate=3600"
